import dholki_green_orange-Edit from ./../../images/gallery/../images/dec31gallery/dholki/dholki_green_orange-Edit.jpg
import dholki_green_orange-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/dholki_green_orange-Edit.webp
import dholki_orange_pink-Edit from ./../../images/gallery/../images/dec31gallery/dholki/dholki_orange_pink-Edit.jpg
import dholki_orange_pink-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/dholki_orange_pink-Edit.webp
import dholki_pink_orange-Edit from ./../../images/gallery/../images/dec31gallery/dholki/dholki_pink_orange-Edit.jpg
import dholki_pink_orange-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/dholki_pink_orange-Edit.webp
import dholki_yellow_green-Edit from ./../../images/gallery/../images/dec31gallery/dholki/dholki_yellow_green-Edit.jpg
import dholki_yellow_green-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/dholki_yellow_green-Edit.webp
import orange_white_dholki-Edit from ./../../images/gallery/../images/dec31gallery/dholki/orange_white_dholki-Edit.jpg
import orange_white_dholki-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/orange_white_dholki-Edit.webp
import sholki_pink_green-Edit from ./../../images/gallery/../images/dec31gallery/dholki/sholki_pink_green-Edit.jpg
import sholki_pink_green-Edit.webp from ./../../images/gallery/../images/dec31gallery/dholki/sholki_pink_green-Edit.webp
